### ISSUE TITLE
Cannot add api key

### ISSUE THREAD

**Issue by rpoovey** [0x101-Cyber-Security/NetLock-RMM#21]
When trying to save the API key in the web console I am given the error:

>Unauthorized access. Please verify your API key and ensure the Member Portal API is reachable.

Running version: 2.5.0.1 (docker stack)

**Comment by 0x100001** [comment]
I verified the api is working normal. Make sure api.members.netlockrmm.com is not blocked in your firewall.

**Comment by rpoovey** [comment]
I have no outbound firewall blocking enabled. 

Installed telnet on the netlock-rmm-server container and tested. 
![Image](https://github.com/user-attachments/assets/78413d50-4a1d-4e03-8252-4941d5007d31)

I am on the free self-hosted level right now, does that affect this? Are there any other logs I can gather for you?

**Comment by 0x100001** [comment]
No it does not affect that.

You can create logs: https://docs.netlockrmm.com/en/debugging

Make sure to not leak sensitive information here.

**Comment by rpoovey** [comment]
I created the `debug.txt` file in each docker containers logs directory, restarted the stack and recreated the issue. No logs were generated. Could the issue be on my account? The email is under `netlock@0896c69e.com` if you are able to check my user.

**Comment by rpoovey** [comment]
Weird, I only see 1 account membership in my web UI. #564574

**Comment by rpoovey** [comment]
What the heck. Maybe I'll trash the database and recreate. Any other suggestions?

**Comment by 0x100001** [comment]
I dont know your setup and without the debug logs its hard to judge. Make sure you are not using MariaDB. The only weird issues ive seen is people not using mysql.

**Comment by rpoovey** [comment]
Yeah, my stack is the same really. Except I'm using an external mysql server instead of docker and disabled https in the compose ports and also appsettings.json

I finally see the logs. It doesn't append to debug.txt instead makes files called `Logs\debug.txt`

`Logs\error.txt` has
```
{"type":"Error","date":"03/12/2025 16:01:51","reported_by":"Microsoft_Defender_Firewall.Rule_Inbound","_event":"Add NetLock service rule (outbound)","content":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027type\u0027)\n   at System.ArgumentNullException.Throw(String paramName)\n   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)\n   at NetLock_RMM_Web_Console.Microsoft_Defender_Firewall.Rule_Inbound(String port) in C:\\Users\\NicoMak\\NetLock\\NetLock-RMM\\NetLock-RMM-Web-Console\\Classes\\Microsoft_Defender_Firewall\\Handler.cs:line 35"}
{"type":"Error","date":"03/12/2025 16:01:51","reported_by":"Microsoft_Defender_Firewall.Rule_Outbound","_event":"Add NetLock service rule (outbound)","content":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027type\u0027)\n   at System.ArgumentNullException.Throw(String paramName)\n   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)\n   at NetLock_RMM_Web_Console.Microsoft_Defender_Firewall.Rule_Outbound(String port) in C:\\Users\\NicoMak\\NetLock\\NetLock-RMM\\NetLock-RMM-Web-Console\\Classes\\Microsoft_Defender_Firewall\\Handler.cs:line 69"}
{"type":"Error","date":"03/12/2025 16:01:52","reported_by":"Classes.MySQL.Handler.Quick_Reader","_event":"query: SELECT * FROM settings; item: smtp","content":"Table \u0027netlock.settings\u0027 doesn\u0027t exist"}
{"type":"Error","date":"03/12/2025 16:01:52","reported_by":"Classes.MySQL.Handler.Quick_Reader","_event":"query: SELECT * FROM settings; item: files_api_key","content":"Table \u0027netlock.settings\u0027 doesn\u0027t exist"}
```

**Comment by rpoovey** [comment]
> I dont know your setup and without the debug logs its hard to judge. Make sure you are not using MariaDB. The only weird issues ive seen is people not using mysql.

Ahhh, this might be it. I have a mariadb cluster behind a load balancer that I use for all my deployments. I'll pivot to a mysql container in the stack and see if that works.

**Comment by 0x100001** [comment]
> > I dont know your setup and without the debug logs its hard to judge. Make sure you are not using MariaDB. The only weird issues ive seen is people not using mysql.
> 
> Ahhh, this might be it. I have a mariadb cluster behind a load balancer that I use for all my deployments. I'll pivot to a mysql container in the stack and see if that works. 

I am sure this will solve your issues. The log you provided makes it clear that this happened due to MariaDB usage.

**Comment by rpoovey** [comment]
Unfortunately, switching to mysql docker container still gives me the same error. 

```yaml
services:
  netlock-db:
    image: mysql:8.0
    container_name: netlock-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: netlock
      MYSQL_USERNAME: netlock
      MYSQL_USER_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /volume1/docker/Netlock/mysql/data:/var/lib/mysql
    expose:
      - 3306
    restart: unless-stopped
    command: --disable-log-bin
  netlock-web-console:
    image: nicomak101/netlock-rmm-web-console:latest
    container_name: netlock-web-console
    ports:
      - 8011:80
    volumes:
      - /volume1/docker/Netlock/web_console/appsettings.json:/app/appsettings.json
      - /volume1/docker/Netlock/web_console/logs:/var/0x101 Cyber
        Security/NetLock RMM/Web Console/
    restart: unless-stopped
  netlock-rmm-server:
    image: nicomak101/netlock-rmm-server:latest
    container_name: netlock-rmm-server
    ports:
      - 7080:7080
    volumes:
      - /volume1/docker/Netlock/server/appsettings.json:/app/appsettings.json
      - /volume1/docker/Netlock/server/files:/app/www/private/files
      - /volume1/docker/Netlock/server/logs:/var/0x101 Cyber Security/NetLock
        RMM/Server/
    restart: unless-stopped
```
Web console appsettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Error",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoint": {
      "Http": {
        "Enabled": true,
        "Port": 80
      },
      "Https": {
        "Enabled": false,
        "Port": 443,
        "Force": false,
        "Hsts": {
          "Enabled": false
        }
      }
    }
  },
  "NetLock_Remote_Server": {
    "Server": "netlock-rmm-server",
    "Port": 7080,
    "UseSSL": false
  },
  "NetLock_File_Server": {
    "Server": "netlock-rmm-server",
    "Port": 7080,
    "UseSSL": false
  },
  "MySQL": {
    "Server": "netlock-db",
    "Port": 3306,
    "Database": "netlock",
    "User": "netlock",
    "Password": "REDACTED",
    "SslMode": "None",
    "AdditionalConnectionParameters": "AllowPublicKeyRetrieval=True;"
  },
  "LettuceEncrypt": {
    "Enabled": false,
    "AcceptTermsOfService": true,
    "DomainNames": [ "demo.netlockrmm.com" ],
    "EmailAddress": "example@0x101-cyber-security.de",
    "AllowedChallengeTypes": "Http01, TlsAlpn01, Dns01",
    "CertificateStoredPfxPassword": "Password123"
  },
  "Webinterface": {
    "Title": "REDACTED",
    "Language": "en-US",
    "Membership_Reminder": false
  },
  "Members_Portal_Api": {
    "Enabled": true,
    "Cloud": false
  }
}
```
server appsettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Error",
      "Microsoft.Hosting.Lifetime": "Warning",
      "Microsoft.AspNetCore.SignalR": "Error",
      "Microsoft.AspNetCore.Http.Connections": "Error"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoint": {
      "Http": {
        "Enabled": true,
        "Port": 7080
      },
      "Https": {
        "Enabled": false,
        "Port": 7443,
        "Force": false,
        "Hsts": {
          "Enabled": false
        }
      }
    },
    "Roles": {
      "Comm": true,
      "Update": true,
      "Trust": true,
      "Remote": true,
      "Notification": true,
      "File": true,
      "LLM": true
    }
  },
  "MySQL": {
    "Server": "netlock-db",
    "Port": 3306,
    "Database": "netlock",
    "User": "netlock",
    "Password": "REDACTED",
    "SslMode": "None",
    "AdditionalConnectionParameters": "AllowPublicKeyRetrieval=True;"
  },
  "LettuceEncrypt": {
    "Enabled": false,
    "AcceptTermsOfService": true,
    "DomainNames": [ "demo.netlockrmm.com" ],
    "EmailAddress": "nico.mak@0x101-cyber-security.de",
    "AllowedChallengeTypes": "Http01, TlsAlpn01, Dns01",
    "CertificateStoredPfxPassword": "Password123"
  },
  "Members_Portal_Api": {
    "Enabled": true
  }
}
